"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";
import { api, apiMessage } from "@/lib/api";
import { DashboardHeading, EmptyState, ErrorState, LoadingState } from "./states";

const illustrativeConfiguration = { hardware_name: "Illustrative GPU workstation", purchase_cost: "3600", useful_lifetime_months: 36, monthly_electricity: "40", monthly_maintenance: "60", available_memory_gb: "48", estimated_requests_per_second: "2", utilization: "0.25", supported_model: "illustrative-local-8b", context_limit: 32768, currency: "USD", benchmark_source: "User estimate; not a measured benchmark" };

export function LocalModelEconomics() {
  const client = useQueryClient();
  const [selected, setSelected] = useState("");
  const [error, setError] = useState("");
  const configurations = useQuery({ queryKey: ["local-model-configurations"], queryFn: async () => { const response = await api.GET("/api/v1/local-model-configurations"); if (!response.data) throw response.error; return response.data.items; } });
  const create = useMutation({ mutationFn: async () => { const response = await api.POST("/api/v1/local-model-configurations", { body: illustrativeConfiguration }); if (response.error) throw response.error; return response.data; }, onSuccess: async (item) => { setSelected(item!.id); setError(""); await client.invalidateQueries({ queryKey: ["local-model-configurations"] }); }, onError: (cause) => setError(apiMessage(cause)) });
  const compare = useMutation({ mutationFn: async (id: string) => { const response = await api.POST("/api/v1/local-model-configurations/{configurationID}/compare", { params: { path: { configurationID: id } }, body: { monthly_requests: 100000, hosted_cost_per_request: "0.01", required_memory_gb: "16", required_context_tokens: 8000 } }); if (response.error) throw response.error; return response.data; }, onError: (cause) => setError(apiMessage(cause)) });
  if (configurations.isPending) return <LoadingState />;
  if (configurations.isError) return <ErrorState message={apiMessage(configurations.error)} />;
  const activeID = selected || configurations.data[0]?.id || "";
  const chart = compare.data ? [{ execution: "Hosted", monthly: Number(compare.data.hosted_monthly_cost) }, { execution: "Local", monthly: Number(compare.data.local_monthly_cost) }] : [];
  return <><DashboardHeading eyebrow="Infrastructure economics" title="Hosted versus local models" description="Simulate capacity and cost with explicit hardware assumptions. Quality and throughput remain unverified until measured." /><section className="dashboard-panel"><div className="panel-title"><div><h2>Hardware configurations</h2><p>Create an illustrative configuration, then replace every estimate with measured operational data.</p></div><button className="button" type="button" disabled={create.isPending} onClick={() => create.mutate()}>Add illustrative configuration</button></div>{configurations.data.length ? <label className="evaluation-label">Configuration<select value={activeID} onChange={(event) => setSelected(event.target.value)}>{configurations.data.map((item) => <option key={item.id} value={item.id}>{item.hardware_name} · {item.supported_model}</option>)}</select></label> : <EmptyState title="No local hardware configuration" message="Add an illustrative configuration to inspect the methodology." />}<button className="button" type="button" disabled={!activeID || compare.isPending} onClick={() => compare.mutate(activeID)}>Compare 100,000 monthly requests</button>{error && <p role="alert" className="form-error">{error}</p>}</section>{compare.data && <div className="dashboard-grid"><section className="metric-grid wide"><article><span>Supported</span><strong>{compare.data.supported ? "Candidate" : "No"}</strong><small>{compare.data.constraints.join(", ") || "Capacity constraints pass"}</small></article><article><span>Local monthly</span><strong>{compare.data.currency} {Number(compare.data.local_monthly_cost).toFixed(2)}</strong><small>Includes amortization</small></article><article><span>Estimated savings</span><strong>{compare.data.currency} {Number(compare.data.estimated_monthly_savings).toFixed(2)}</strong><small>Not verified</small></article><article><span>Break-even</span><strong>{compare.data.estimated_break_even_months ?? "Unavailable"}</strong><small>months</small></article></section><section className="dashboard-panel"><h2>Monthly cost comparison</h2><div className="chart" aria-label="Hosted versus local monthly cost chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="execution" /><YAxis /><Tooltip /><Bar dataKey="monthly" fill="#65e6bd" /></BarChart></ResponsiveContainer></div></section><section className="dashboard-panel"><h2>Capacity and limitations</h2><dl className="result-list"><div><dt>Monthly capacity</dt><dd>{compare.data.monthly_capacity}</dd></div><div><dt>Hardware amortization</dt><dd>{compare.data.currency} {compare.data.hardware_amortization}</dd></div><div><dt>Local cost per request</dt><dd>{compare.data.local_cost_per_request ?? "Unavailable"}</dd></div></dl><p>{compare.data.methodology}</p><p>This simulation is not a benchmark and does not establish candidate model quality.</p></section></div>}</>;
}
