/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkloads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads/{workloadID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLLMCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsLatency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendationID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendationID}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendationID}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendationID}/audit-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecommendationAuditHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation-datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvaluationDatasets"];
        put?: never;
        post: operations["createEvaluationDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation-datasets/{datasetID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvaluationDataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEvaluationRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation-runs/{runID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvaluationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/local-model-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLocalModelConfigurations"];
        put?: never;
        post: operations["createLocalModelConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/local-model-configurations/{configurationID}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compareLocalModelEconomics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                request_id: string;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        Session: {
            /** Format: date-time */
            expires_at: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** @enum {string} */
            role: "owner" | "admin" | "engineer" | "finance" | "viewer";
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            slug: string;
            environment: string;
            monthly_budget: string;
            currency: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Workload: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            name: string;
            slug: string;
            type: string;
            owner: string;
            criticality: string;
            quality_requirement: string;
            privacy_classification: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LLMCall: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            workload_id: string;
            external_call_id: string;
            provider: string;
            model: string;
            estimated_cost: string;
            currency: string;
            redacted_prompt_preview?: string;
            redacted_response_preview?: string;
            /** Format: date-time */
            created_at: string;
            idempotent_replay: boolean;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            limit: number;
            offset: number;
        };
        WorkloadPage: {
            items: components["schemas"]["Workload"][];
            limit: number;
            offset: number;
        };
        CallPage: {
            items: components["schemas"]["LLMCall"][];
            limit: number;
            offset: number;
        };
        AnalyticsOverview: {
            observed_cost: string;
            previous_period_cost: string;
            estimated_monthly_projection: string;
            currency: string;
            call_count: number;
            input_tokens: number;
            output_tokens: number;
            cached_input_tokens: number;
            average_latency_ms: string;
            error_rate: string;
            retry_rate: string;
            projection_method: string;
        };
        CostPoint: {
            key: string;
            cost: string;
            calls: number;
            currency: string;
        };
        DailyPoint: {
            /** Format: date */
            date: string;
            cost: string;
            calls: number;
        };
        CostAnalytics: {
            dimension: string;
            breakdown: components["schemas"]["CostPoint"][];
            daily: components["schemas"]["DailyPoint"][];
            currency: string;
        };
        TokenSummary: {
            input: number;
            output: number;
            cached_input: number;
        };
        LatencySummary: {
            average_ms: string;
            p50_ms: string;
            p95_ms: string;
        };
        ErrorSummary: {
            calls: number;
            errors: number;
            retried_calls: number;
            error_rate: string;
            retry_rate: string;
        };
        Recommendation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workload_id: string;
            recommendation_type: string;
            priority: string;
            confidence_level: string;
            status: string;
            currency: string;
            quality_risk: string;
            operational_risk: string;
            required_next_action: string;
            rule_version: string;
            confidence: string;
            estimated_monthly_savings: string;
            estimated_implementation_cost: string;
            estimated_break_even_months?: string | null;
            reason_codes: string[];
            evidence_summary: {
                [key: string]: unknown;
            };
            confidence_inputs: {
                [key: string]: unknown;
            };
            current_execution: {
                [key: string]: unknown;
            };
            proposed_execution: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        RecommendationReviewRequest: {
            reason?: string;
        };
        AuditEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actor_user_id: string;
            action: string;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        EvaluationRule: {
            /** @enum {string} */
            type: "exact_match" | "classification_match" | "json_schema" | "required_fields";
            field?: string;
            fields?: string[];
            required?: string[];
            types?: {
                [key: string]: "string" | "number" | "boolean" | "array" | "object" | "null";
            };
        };
        EvaluationCase: {
            /** Format: uuid */
            id?: string;
            sanitized_input: unknown;
            expected_output: unknown;
            validation_rules: components["schemas"]["EvaluationRule"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        EvaluationRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dataset_id: string;
            candidate_execution: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed";
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            total_cases: number;
            passed_cases: number;
            failed_cases: number;
            average_latency_ms: string;
            estimated_cost: string;
            currency: string;
            results: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        EvaluationDataset: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workload_id: string;
            name: string;
            description: string;
            source: string;
            privacy_classification: string;
            case_count: number;
            cases?: components["schemas"]["EvaluationCase"][];
            runs?: components["schemas"]["EvaluationRun"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateEvaluationDataset: {
            /** Format: uuid */
            workload_id: string;
            name: string;
            description?: string;
            source: string;
            /** @enum {string} */
            privacy_classification: "public" | "internal" | "confidential" | "restricted";
            cases: components["schemas"]["EvaluationCase"][];
        };
        CreateEvaluationRun: {
            /** Format: uuid */
            dataset_id: string;
            candidate_execution: {
                /** @enum {string} */
                adapter: "deterministic_mock";
                /** @enum {string} */
                mode: "expected" | "echo" | "fixed";
                currency: string;
            } & {
                [key: string]: unknown;
            };
        };
        LocalModelConfigurationInput: {
            hardware_name: string;
            purchase_cost: string;
            useful_lifetime_months: number;
            monthly_electricity: string;
            monthly_maintenance: string;
            available_memory_gb: string;
            estimated_requests_per_second: string;
            utilization: string;
            supported_model: string;
            context_limit: number;
            currency: string;
            benchmark_source: string;
        };
        LocalModelConfiguration: components["schemas"]["LocalModelConfigurationInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LocalModelComparisonInput: {
            monthly_requests: number;
            hosted_cost_per_request: string;
            required_memory_gb: string;
            required_context_tokens: number;
        };
        LocalModelComparison: {
            supported: boolean;
            constraints: string[];
            monthly_capacity: string;
            hardware_amortization: string;
            local_monthly_cost: string;
            hosted_monthly_cost: string;
            local_cost_per_request?: string | null;
            estimated_monthly_savings: string;
            estimated_break_even_months?: string | null;
            currency: string;
            methodology: string;
        };
    };
    responses: {
        /** @description API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        From: string;
        To: string;
        Timezone: string;
        ProjectID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: string;
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listWorkloads: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                project_id?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workload page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadPage"];
                };
            };
        };
    };
    getWorkload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workloadID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workload"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listLLMCalls: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                project_id?: string;
                workload_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallPage"];
                };
            };
        };
    };
    getAnalyticsOverview: {
        parameters: {
            query?: {
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
                timezone?: components["parameters"]["Timezone"];
                project_id?: string;
                workload_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
        };
    };
    getAnalyticsCosts: {
        parameters: {
            query?: {
                dimension?: "project" | "workload" | "provider" | "model" | "task";
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
                timezone?: components["parameters"]["Timezone"];
                project_id?: string;
                workload_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostAnalytics"];
                };
            };
        };
    };
    getAnalyticsTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSummary"];
                };
            };
        };
    };
    getAnalyticsLatency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencySummary"];
                };
            };
        };
    };
    getAnalyticsErrors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Error analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSummary"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query?: {
                status?: string;
                priority?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Recommendation"][];
                    };
                };
            };
        };
    };
    getRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    acceptRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendationID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecommendationReviewRequest"];
            };
        };
        responses: {
            /** @description Accepted for evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    rejectRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendationID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationReviewRequest"];
            };
        };
        responses: {
            /** @description Rejected recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getRecommendationAuditHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listEvaluationDatasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation datasets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EvaluationDataset"][];
                    };
                };
            };
        };
    };
    createEvaluationDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationDataset"];
            };
        };
        responses: {
            /** @description Dataset created atomically with sanitized cases */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDataset"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getEvaluationDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset cases and runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDataset"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createEvaluationRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRun"];
            };
        };
        responses: {
            /** @description Deterministic candidate evaluation completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getEvaluationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation run results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listLocalModelConfigurations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local model configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LocalModelConfiguration"][];
                    };
                };
            };
        };
    };
    createLocalModelConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalModelConfigurationInput"];
            };
        };
        responses: {
            /** @description Configuration created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalModelConfiguration"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    compareLocalModelEconomics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configurationID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalModelComparisonInput"];
            };
        };
        responses: {
            /** @description Hosted and local economics comparison */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalModelComparison"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
